[package]
name = "lym-cli-web"
version = "1.0.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc-2"
rocket_dyn_templates = { version = "0.1.0-rc-2", features = ["handlebars"] }
shuttle-rocket = "0.39.0"
shuttle-runtime = "0.39.0"
